In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [2]:
data = {
    "name":["A","C","D","B","E","A","E","C"],
    "dept_id":["s1","s4","s5","s2","s3","s1","s4","s5"],
    "d_name" :["Analyst","Developer","Engineer","Trainer","UI Developer","Developer","Engineer","Analyst"],
    "salary" :[15000,20000,23000,18000,21000,19000,25000,27000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  name dept_id        d_name  salary
0    A      s1       Analyst   15000
1    C      s4     Developer   20000
2    D      s5      Engineer   23000
3    B      s2       Trainer   18000
4    E      s3  UI Developer   21000
5    A      s1     Developer   19000
6    E      s4      Engineer   25000
7    C      s5       Analyst   27000

In [5]:
x = df.drop(columns='salary')
y = df['salary']

In [6]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [7]:
df

  name dept_id        d_name  salary
0    A      s1       Analyst   15000
1    C      s4     Developer   20000
2    D      s5      Engineer   23000
3    B      s2       Trainer   18000
4    E      s3  UI Developer   21000
5    A      s1     Developer   19000
6    E      s4      Engineer   25000
7    C      s5       Analyst   27000

# Scenario 1

* Error --> ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)

In [8]:
encoder = OrdinalEncoder(categories=[['Developer','Analyst','Enginneer','Trainer',"UI Developer"],["s1",'s2','s5','s4','s3']],
                         handle_unknown="use_encoded_value",
                         unknown_value=-1
                         )

encoder.fit_transform(xtrain[['d_name','dept_id']])
# encoder.fit_transform(xtrain[['d_name','dept_id',"name"]])

#Error --> ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)

array([[ 1.,  0.],
       [ 1.,  2.],
       [-1.,  2.],
       [ 4.,  4.],
       [ 3.,  1.],
       [-1.,  3.]])

# Scenario 2

* Every value is unknown now! So ,it assigns -1 for all the values.

In [9]:
encoder = OrdinalEncoder(categories=[['Developer','Analyst','Enginneer','Trainer',"UI Developer"],["s1",'s2','s5','s4','s3']],
                         handle_unknown="use_encoded_value",
                         unknown_value=-1
                         )

encoder.fit_transform(xtrain[['dept_id','d_name']])

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

# Scenario 3

* If the value on the Category present it gives a meaningful value if not present it gives (-1)

In [10]:
encoder = OrdinalEncoder(categories=[['Developer','Analyst','Enginneer','AI Engineer'],["s1",'s2','s5','s4','s3']],
                         handle_unknown="use_encoded_value",
                         unknown_value=-1
                         )

encoder.fit_transform(xtrain[['d_name','dept_id']])

array([[ 1.,  0.],
       [ 1.,  2.],
       [-1.,  2.],
       [-1.,  4.],
       [-1.,  1.],
       [-1.,  3.]])